# Generated by Django 4.2.4 on 2023-08-24 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
        ('user', '0002_user_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comunidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.comunidad'),
        ),
    ]
