# Generated by Django 4.2.4 on 2023-08-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_comunidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(max_length=1, null=True, verbose_name='Tipo'),
        ),
    ]
