# Generated by Django 4.2.4 on 2023-08-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(default='a', max_length=1, null=True, verbose_name='Tipo'),
        ),
    ]
