# Generated by Django 4.2.4 on 2023-10-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_comunidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No informado', 'No informar')], default='No informado', verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='edad',
            field=models.CharField(choices=[('0-14 años:', '0-14 años'), ('15-24 años', '15-24 años'), ('25-54 años', '25-54 años'), ('55-64 años', '55-64 años'), ('65 años y más', '65 años y más')], default='No informado', verbose_name='Rango etario'),
        ),
    ]
