# Generated by Django 4.2.4 on 2023-10-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_gender_alter_user_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='edad',
            field=models.CharField(choices=[('18-24 años', '18-24 años'), ('25-54 años', '25-54 años'), ('55-64 años', '55-64 años'), ('65 años y más', '65 años y más')], default='No informado', verbose_name='Rango etario'),
        ),
    ]
