# Generated by Django 4.2.5 on 2023-11-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='caudal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='datos',
            name='conductividad',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='datos',
            name='humedad',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='datos',
            name='pH',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='datos',
            name='temperatura',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='datos',
            name='turbiedad',
            field=models.FloatField(default=0),
        ),
    ]
