# Generated by Django 4.2.4 on 2023-08-24 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vertiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('desc', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('ubicación', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('caudal', models.IntegerField(default=0)),
                ('pH', models.IntegerField(default=0)),
                ('conductividad', models.IntegerField(default=0)),
                ('turbiedad', models.IntegerField(default=0)),
                ('temperatura', models.IntegerField(default=0)),
                ('humedad', models.IntegerField(default=0)),
                ('comunidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.comunidad')),
            ],
            options={
                'verbose_name': 'Vertiente',
                'verbose_name_plural': 'Vertientes',
                'db_table': 'vertiente',
                'ordering': ['id'],
            },
        ),
    ]
