# Generated by Django 4.2.4 on 2023-11-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_alter_datos_caudal_alter_datos_conductividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='contacto_encargado',
            field=models.CharField(default=11111, max_length=100, verbose_name='Contacto del encargado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comunidad',
            name='encargado',
            field=models.CharField(default=1, max_length=100, verbose_name='Encargado'),
            preserve_default=False,
        ),
    ]
