# Generated by Django 4.2.4 on 2023-08-30 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_vertiente'),
    ]

    operations = [
        migrations.CreateModel(
            name='kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.IntegerField(default=0)),
                ('ubicación', models.CharField(max_length=200, verbose_name='Ubicación')),
            ],
        ),
        migrations.CreateModel(
            name='datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caudal', models.IntegerField(default=0)),
                ('pH', models.IntegerField(default=0)),
                ('conductividad', models.IntegerField(default=0)),
                ('turbiedad', models.IntegerField(default=0)),
                ('temperatura', models.IntegerField(default=0)),
                ('humedad', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('kit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.kit')),
                ('vertiente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.vertiente')),
            ],
        ),
    ]
