# Generated by Django 4.2.4 on 2023-08-30 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_kit_datos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datos',
            options={'ordering': ['id'], 'verbose_name': 'Dato', 'verbose_name_plural': 'Datos'},
        ),
        migrations.AlterModelOptions(
            name='kit',
            options={'ordering': ['id'], 'verbose_name': 'Modelo', 'verbose_name_plural': 'Modelos'},
        ),
        migrations.AlterModelTable(
            name='datos',
            table='datos',
        ),
        migrations.AlterModelTable(
            name='kit',
            table='modelo',
        ),
    ]
