# Generated by Django 4.2.4 on 2023-08-30 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_alter_datos_options_alter_kit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kit',
            options={'ordering': ['id'], 'verbose_name': 'Kit', 'verbose_name_plural': 'Kits'},
        ),
        migrations.AlterModelTable(
            name='kit',
            table='Kit',
        ),
    ]
