# Generated by Django 4.2.4 on 2023-09-06 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_alter_kit_options_alter_kit_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='kit',
        ),
        migrations.AddField(
            model_name='kit',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kit',
            name='vertiente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleo.vertiente'),
        ),
    ]
