# Generated by Django 4.2.4 on 2023-10-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_remove_datos_kit_kit_is_active_kit_vertiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='vertiente',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vertiente',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
