# Generated by Django 4.2.4 on 2023-10-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0007_vertiente_latitud_vertiente_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='ubicación',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='vertientes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vertiente',
            name='desc',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='vertiente',
            name='ubicación',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación'),
        ),
    ]
